# Generated by Django 4.2.15 on 2025-09-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estado_studentprofile_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externalstudent',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
