# Generated by Django 5.2.6 on 2025-10-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_aluno_cep_alter_aluno_numero_identidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='professores',
        ),
        migrations.DeleteModel(
            name='Convite',
        ),
    ]
