# Generated by Django 5.2.6 on 2025-10-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_curso_professores_delete_convite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
    ]
