# Generated by Django 5.2.6 on 2025-10-06 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_user_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
