# Generated by Django 5.2.6 on 2025-10-06 20:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curso',
            options={'ordering': ['nome'], 'verbose_name': 'Curso', 'verbose_name_plural': 'Cursos'},
        ),
        migrations.AddField(
            model_name='curso',
            name='data_fim_curso',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fim do Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='data_fim_inscricoes',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fim das Inscrições'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='data_inicio_curso',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Início do Curso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='data_inicio_inscricoes',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Início das Inscrições'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='descricao_curta',
            field=models.CharField(default='', help_text='Texto que aparecerá nos cards do curso.', max_length=200, verbose_name='Descrição Curta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='curso',
            name='requisitos',
            field=models.TextField(blank=True, verbose_name='Requisitos do Curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='status',
            field=models.CharField(choices=[('AGENDADO', 'Agendado'), ('INSCRIÇÕES ABERTAS', 'Inscrições Abertas'), ('EM ANDAMENTO', 'Em Andamento'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado')], default='AGENDADO', max_length=20, verbose_name='Status do Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='carga_horaria',
            field=models.PositiveIntegerField(verbose_name='Carga Horária (em horas)'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='criador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_criados', to='api.professor', verbose_name='Professor Criador'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='descricao',
            field=models.TextField(verbose_name='Descrição Completa'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome do Curso'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='vagas_externas',
            field=models.PositiveIntegerField(default=10, verbose_name='Vagas para Alunos Externos'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='vagas_internas',
            field=models.PositiveIntegerField(default=20, verbose_name='Vagas para Alunos Internos'),
        ),
    ]
