# Generated by Django 5.2.6 on 2025-10-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricaoaluno',
            name='tipo_vaga',
            field=models.CharField(choices=[('INTERNO', 'Interno'), ('EXTERNO', 'Externo'), ('NI', 'ni')], max_length=10),
        ),
    ]
