# Generated by Django 5.2.6 on 2025-10-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_inscricaoaluno_tipo_vaga'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricaoaluno',
            name='matricula',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Matrícula(para vagas internas)'),
        ),
    ]
